### ISSUE TITLE
代码bug

### ISSUE THREAD

**Issue by chengweige** [meiqua/shape_based_matching#1]
windows平台，opencv249
angle_test();
getLabel(int quantized)  //quantized == 0
CV_Error(CV_StsBadArg, "Invalid value of quantized parameter");

**Comment by meiqua** [comment]
已修复。这个是因为计算方向需要局部3x3类统计到一定数量才算：  
272行 static const int NEIGHBOR_THRESHOLD = 5;  
本来我实验的时候发现改高点会出现这个bug，忘记往主代码里加了。  
getlabel前加个>0判断就好
