### ISSUE TITLE
代码重构

### ISSUE THREAD

**Issue by brunolinux** [meiqua/shape_based_matching#105]
您好, 我在看完您的代码和论文后,
因为 line2Dup 文件实在太长, 我把它重构了, 同时把里面的 todo 部分按照自己的理解修改了一些.
大部分和您的代码是相同的.
同时大部分功能都写了 测试 (不是很正规) 
代码库在这里
https://github.com/brunolinux/shape_matching
由于时间原因, 并没有添加 fusion 部分的内容.
如果您感兴趣的话, 看是否合并到您的代码库里面.

**Comment by meiqua** [comment]
厉害了。我大概看了下，改动有点多，短时间内我没有办法确认正确性，而且没有大的问题的话我倾向于不改代码。  
里面的todo都是最开始版本的linemod留下来的；如果您有更好的想法的话，欢迎一起讨论，然后提PR修改
