### ISSUE TITLE
VS2015 fusion 下的MIPP 开启指令集时报错

### ISSUE THREAD

**Issue by lhangggg** [meiqua/shape_based_matching#106]
用最新的的fusion 在win系统 VS2015 下 开启SSE，然后打开use_simd=true报错。mipp的errorMessage函数返回的错误码是：mipp::mul<int32_t> (SSE2) is undefiuned!"。然后我查看mipp_impl_sse.hxx好像确实没有int32_t 的mul 实例。自己手动在该文件下加上这个格式的实现后，编译报错：“mipp::mul”: 非法使用显式参数。 请教大哥，有遇到过这个问题码？有什么办法可以处理？

**Comment by meiqua** [comment]
确定是最新的吗？这个问题之前碰到过，应该已经好了，在[这一行](https://github.com/meiqua/shape_based_matching/blob/00bbd5df64fbc1562a46f7a6d659bbd5379961fb/MIPP/mipp_impl_SSE.hxx#L2049)有

**Comment by lhangggg** [comment]
检查了下， 发现我用的是icp 下的MIPP，混了， 感谢大佬帮助。
