### ISSUE TITLE
inv_light采用fussion 改写运行匹配不到

### ISSUE THREAD

**Issue by qq61786631** [meiqua/shape_based_matching#119]
在现有fussion代码基础上，改写了下代码， 感觉改动比较大的就是角度划分方向这块，用fussion出来的结果和之前代码结果不一致，结果匹配个数都是空的~ 请博主帮看看

if (mag > threshold * threshold)
{
    
    bool isY = dy_(i) < 0;
    int32_t x = dx_(i);
    int32_t y = ((dy_(i) < 0) ? -dy_(i) : dy_(i)) << 15;
    uint8_t label;
    if (x > 0)
    {
        if (y < x * TG1125)label = 0;
        else if (y < x * TG3375)label = 1;
        else if (y < x * TG5625)label = 2;
        else if (y < x * TG7875)label = 3;
        else label = 4;
    }
    else if (x < 0)
    {
        if (y < x * TG10125)label = 4;
        else if (y < x * TG12375)label = 5;
        else if (y < x * TG14625)label = 6;
        else if (y < x * TG16875)label = 7;
        else label = 8;
    }
    else
    {
        label = 4;
    }
  uint8_t label_t=isY ? 16 - label : label;
  quantized_unfiltered(i) = label_t==16? 0 : label_t;
}

**Comment by meiqua** [comment]
我记得inv_light改动有很多地方，只改这里应该不行
