### ISSUE TITLE
windows下openmp报错

### ISSUE THREAD

**Issue by KayChanGeek** [meiqua/shape_based_matching#12]
![image](https://user-images.githubusercontent.com/22118394/54602104-ac14fc00-4a7b-11e9-8cfb-ba1aedcd57c0.png)
如图所示：Windows下VS打开openmp编译报以下错误，关闭OMP则可以用。这是啥情况？

**Comment by meiqua** [comment]
我查了下，是因为vs不支持高级点的openmp指令。我手动模拟了下：[custom reduction](https://gist.github.com/meiqua/4d92b5e3bf8c22d38a73e01683476e1c)

**Comment by oUp2Uo** [comment]
icp的60多行那，也有类似的报错应该

**Comment by meiqua** [comment]
对 这样写好理解些

**Comment by xinsuinizhuan** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/22118394/54602104-ac14fc00-4a7b-11e9-8cfb-ba1aedcd57c0.png)
> 如图所示：Windows下VS打开openmp编译报以下错误，关闭OMP则可以用。这是啥情况？

最后怎么解决的？我也遇到了同样的问题？

**Comment by xinsuinizhuan** [comment]
> 
> 
> 查了下，是因为vs不支持高级点的openmp指令。手动模拟了下：[custom reduction](https://gist.github.com/meiqua/4d92b5e3bf8c22d38a73e01683476e1c)，换上应该好了

链接失效了，怎么收到模拟，怎么改？

**Comment by meiqua** [comment]
哦对，被墙了。可以参考[这个](https://gist.githubusercontent.com/meiqua/4d92b5e3bf8c22d38a73e01683476e1c/raw/ecebb314b67b3d1f70c5976686e2b17d745b250b/match.cpp)

**Comment by Mctor** [comment]
> icp的60多行那，也有类似的报错应该
   @meiqua 请问icp这里怎么解决的？链接里的没有涉及到。

**Comment by meiqua** [comment]
@Mctor 跟链接里类似，多一个private相加最后再加起来。当然，最简单的方法是直接注释掉。

**Comment by meiqua** [comment]
Quick Changes:
1. Delete original openmp, paste those lines before the [for loop](https://github.com/meiqua/shape_based_matching/blob/da83a87d8dc502ab035f941f77dbe8d3717ef3ea/line2Dup.cpp#L1141)
``` c++
#ifdef _OPENMP
#pragma omp parallel
    {
#endif
        std::vector<Match> match_private;
#ifdef _OPENMP
#pragma omp for nowait
#endif
    for (int template_id = 0; template_id < template_pyramids.size(); ++template_id)
```

2. Paste those lines after the [insert function](https://github.com/meiqua/shape_based_matching/blob/da83a87d8dc502ab035f941f77dbe8d3717ef3ea/line2Dup.cpp#L1266)
``` c++
        match_private.insert(match_private.end(), candidates.begin(), candidates.end());
    }
#ifdef _OPENMP
#pragma omp critical
        {
#endif
        matches.insert(matches.end(), match_private.begin(), match_private.end());
#ifdef _OPENMP
        }
    }
#endif
```

That's all !
