### ISSUE TITLE
请问一下是否抗缩放呢？

### ISSUE THREAD

**Issue by simentt** [meiqua/shape_based_matching#13]
目的：想识别很小图的轮廓；
但是直接拿很小图的训练，好像很难拿到足够的特征；
直接使用大图训练可以拿到足够多的特征，但是不能直接使用训练的结果去识别小图，我该怎么做呢？

**Comment by meiqua** [comment]
一般能拿到10个点左右，在不复杂的背景下也还好。如果背景复杂导致太多误匹配，可以试试把stride放小点，就是第二个参数{4, 8}改成{2, 4}之类的。这样虽然多费点时间，但是方向扩散也会变小。
当然也可以试试把小图也放大再识别。

**Comment by simentt** [comment]
感谢，这个想法确实有用，很赞。

**Comment by zhirui-gao** [comment]
你好，meiqua！想请教您几个问题。
1.对于很小的物体（长宽50像素左右），模板是自己生成的椭圆，但是这个椭圆有些锯齿状，这个会影响匹配精度吗？
2.如果放大原图，例如3倍或者6倍，放大之后匹配匹配精度会降低吗？
3.使用canny边缘提取之后，再使用模板匹配会更加稳定或者精度更高吗？
谢谢！

**Comment by meiqua** [comment]
@zhirui-gao 
1. 如果精度要求很高是有影响，相当于模板提供的标准位置有一个像素的误差；  
2. 这个不好判断，感觉放大4倍左右精度会稍有提高，更大应该啥没效果了
3. 如果图像质量不好，提canny结果应该会少很多candidate；精度是最后的ICP决定的，影响不大

**Comment by zhirui-gao** [comment]
@meiqua 好的，谢谢了！

**Comment by wusuoweima** [comment]
1.打算使用realsense D435i，通过2D形状识别能获得物体的精准6D姿态吗？
2.在问题1的基础上，对于相机会有远近、视点的变化，怎么解决？ 参考linemod模板生成的方式能解决吗？

**Comment by meiqua** [comment]
@wusuoweima linemod就是为了6D，不过跑的效果没有像2D情况这样接近100%稳定

**Comment by wusuoweima** [comment]
> @wusuoweima linemod就是为了6D，不过跑的效果没有像2D情况这样接近100%稳定
1. 我的模板太小，5cm*1*1, realsense D435i 和Kinect 2精度不够 没办法用linemod或直接用3D
2. 想要同时完成 旋转&缩放，是不是 angle_test 和scale test拼接一下就可以了

**Comment by meiqua** [comment]
@wusuoweima 是的，但6D还需要两个自由度的角度模板
