### ISSUE TITLE
能否把line2Dup库的接口函数封装成和halcon一模一样的？

### ISSUE THREAD

**Issue by libaineu2004** [meiqua/shape_based_matching#140]
能否把line2Dup库的接口函数封装成和halcon一模一样的？函数参数也一模一样的。便于大家使用。
create_shape_model()
find_shape_model()
find_scaled_shape_model()

谢谢！

**Comment by meiqua** [comment]
可以 有时间写下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月15日(周一) 上午10:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [meiqua/shape_based_matching] 能否把line2Dup库的接口函数封装成和halcon一模一样的？ (#140)




 
能否把line2Dup库的接口函数封装成和halcon一模一样的？函数参数也一模一样的。便于大家使用。
 create_shape_model()
 find_shape_model()
 find_scaled_shape_model()
 
谢谢！

**Comment by libaineu2004** [comment]
> 可以 有时间写下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月15日(周一) 上午10:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [meiqua/shape_based_matching] 能否把line2Dup库的接口函数封装成和halcon一模一样的？ (#140) 能否把line2Dup库的接口函数封装成和halcon一模一样的？函数参数也一模一样的。便于大家使用。 create_shape_model() find_shape_model() find_scaled_shape_model() 谢谢！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

很好。谢谢！因为这样有利于该项目的推广使用！让更多使用halcon的工程师，参与进来测试和验证！

**Comment by libaineu2004** [comment]
请问有无时间计划？

**Comment by meiqua** [comment]
可能五月份吧

**Comment by libaineu2004** [comment]
好的，发布之后，我会在halcon论坛http://www.ihalcon.com/，宣传宣传，让更多的工程师参与进来。
辛苦了！

**Comment by libaineu2004** [comment]
> 可能五月份吧

楼主，5月份这个月能完成吗？

**Comment by meiqua** [comment]
不好意思，太忙了，下月一定。

**Comment by libaineu2004** [comment]
> 不好意思，太忙了，下月一定。

谢谢！静待佳音！

**Comment by libaineu2004** [comment]
> 不好意思，太忙了，下月一定。

大佬，请问代码开始写了吗？

**Comment by tyuanyang** [comment]
我也在等！

**Comment by libaineu2004** [comment]
create_scaled_shape_model
create_scaled_shape_model_xld
find_scaled_shape_model
重点还是实现旋转缩放的模板匹配算子。

**Comment by ujsyl** [comment]
me too;wait

**Comment by TigerVersusT** [comment]
差不多得了,封装个接口而已,自己弄嘛
