### ISSUE TITLE
fusion_fix_memo后续会支持mask吗?

### ISSUE THREAD

**Issue by linyugang** [meiqua/shape_based_matching#142]
fusion方法相关分支当前match传入的mask参数处于未使用状态,后续会增加此功能吗?
`assert(mask.empty() && "mask not support yet");`

**Comment by meiqua** [comment]
可能不会了，感觉用的很少。支持ROI倒是不错

**Comment by linyugang** [comment]
> 可能不会了，感觉用的很少。支持ROI倒是不错

感谢回复,我想设置匹配时候的金字塔只匹配到比如第四层应该怎么设置(halcon可以用此方法大幅度提速)?我看代码中的T_at_level数组的值没看懂具体意义.

**Comment by meiqua** [comment]
T_at_level有几个代表有几层，数字代表每层的step size，比如4层可以设成{4 8 8 8}

**Comment by linyugang** [comment]
> T_at_level有几个代表有几层，数字代表每层的step size，比如4层可以设成{4 8 8 8}

实际项目中为了匹配速度,很多时候不需要底层金字塔的,比如我只是匹配6-4层金字塔,不计算1-3层,这种方式现在没有适配吧?

**Comment by meiqua** [comment]
没有。可以直接缩放后再匹配
