### ISSUE TITLE
cuda_icp/icp.cu编译问题

### ISSUE THREAD

**Issue by yingweima2022** [meiqua/shape_based_matching#147]
您好，当我使用cuda_icp时，出现了如下问题：
~/shape_based_matching-sim3/build$ make 
[ 10%] Building NVCC (Device) object cuda_icp/CMakeFiles/cuda_compile_1.dir/scene/edge_scene/cuda_compile_1_generated_edge_scene.cu.o
[ 20%] Building NVCC (Device) object cuda_icp/CMakeFiles/cuda_compile_1.dir/cuda_compile_1_generated_icp.cu.o
/home/shape_based_matching-sim3/cuda_icp/icp.cu(42): error: identifier "Vec11f" is undefined

/home/shape_based_matching-sim3/cuda_icp/icp.cu(44): error: name followed by "::" must be a class or namespace name

2 errors detected in the compilation of "/tmp/tmpxft_00002b5c_00000000-6_icp.cpp1.ii".
CMake Error at cuda_compile_1_generated_icp.cu.o.Release.cmake:280 (message):
  Error generating file
  /home/shape_based_matching-sim3/build/cuda_icp/CMakeFiles/cuda_compile_1.dir//./cuda_compile_1_generated_icp.cu.o

请问vec11f未定义是哪里的问题，谢谢

**Comment by zhenhuamo** [comment]
请问解决了吗？我也出现这个问题
