### ISSUE TITLE
Scene_edge的query函数的idx有越界危险

### ISSUE THREAD

**Issue by oUp2Uo** [meiqua/shape_based_matching#15]
连续检测的程序，碰到idx出现了几次越界，然后程序就直接崩了……

还没查明白为什么会出现idx越界，
不过在计算idx后，加上越界检测，测试基本不再会出现程序崩溃了。

```
 __device__ __host__
    void query(const Vec2f& src_pcd, Vec2f& dst_pcd, Vec2f& dst_normal, bool& valid) const {
        size_t idx = size_t(src_pcd.x + 0.5f) + size_t(src_pcd.y + 0.5f) * width;
		if (idx >= width * height)
		{
			valid = false;
		}
		else
		{
			if(pcd_ptr[idx].x >= 0){
				dst_pcd = pcd_ptr[idx];
				idx = size_t(dst_pcd.x) + size_t(dst_pcd.y) * width;
				dst_normal = normal_ptr[idx];
				valid = true;
			}
			else
			{
				valid = false;
			}
		}
        return;
    }
```

**Comment by meiqua** [comment]
对，你这么一说我想起来了，这里应该跟3d icp的[depth_scene](https://github.com/meiqua/pose_refine/blob/f8ae4ae200c19cdc752f883103a8fd410901df5d/cuda_icp/scene/depth_scene/depth_scene.h#L33)一样
主要是因为icp初始值不好有跑飞的危险。应该分别检测src_pcd.x/y，我改下。

**Comment by oUp2Uo** [comment]
> 对，你这么一说我想起来了，这里应该跟3d icp的[depth_scene](https://github.com/meiqua/pose_refine/blob/f8ae4ae200c19cdc752f883103a8fd410901df5d/cuda_icp/scene/depth_scene/depth_scene.h#L33)一样
> 主要是因为icp初始值不好有跑飞的危险。应该分别检测src_pcd.x/y，我改下。

嗯对，分别检测应该更安全一些

**Comment by meiqua** [comment]
这样
``` c++
        size_t x,y;
        x = size_t(src_pcd.x + 0.5f);
        y = size_t(src_pcd.y + 0.5f);

        if(x >= width || y >= height){
            valid = false;
            return;
        }

        size_t idx = x + y * width;
```

**Comment by oUp2Uo** [comment]
嗯，ok
