### ISSUE TITLE
python_bind中如何将line2Dup.h中的函数make进去呢

### ISSUE THREAD

**Issue by nkstatly** [meiqua/shape_based_matching#150]
您好，我按照readme的方式封装成python，但是Detecor在line2Dup.h中定义的函数貌似并没有封装进，请问有解决办法吗？

**Comment by meiqua** [comment]
是指没有封装哪个函数？可以参考[这里](https://github.com/meiqua/shape_based_matching/blob/4baef0ca67a38fb6e27bdb7c83a6fbe3de4d78ed/pybind11/pybind11.cpp#L37)加

**Comment by nkstatly** [comment]
> 是指没有封装哪个函数？可以参考[这里](https://github.com/meiqua/shape_based_matching/blob/4baef0ca67a38fb6e27bdb7c83a6fbe3de4d78ed/pybind11/pybind11.cpp#L37)加

多谢

**Comment by hungnv21292** [comment]
Hi @meiqua ,
Thanks you for your contribution.

I ran "python3 test.py" and show the issue:
"    import shape_based_matching_py
ModuleNotFoundError: No module named 'shape_based_matching_py'"

Could you please share with me your suggestion.
Thank you very much.

**Comment by meiqua** [comment]
@viethungtsdv Hi, the python module should be installed first. You can find steps in readme of python branch:

> 4. in top level folder, pip3 install ./
