### ISSUE TITLE
Search on high level of pyramid only

### ISSUE THREAD

**Issue by ledaiduongvnth** [meiqua/shape_based_matching#153]
Hi, @meiqua . Thanks for an awesome project.
I know the advantage of using high levels of pyramids in terms of performance. But probably the program is using all of the image pyramids for searching similarities. How to configure the program to train and search for only a high level of a pyramid only. For example level 1/8 of the original resolution?
Thanks!

**Comment by meiqua** [comment]
Hi, currently it's not supported by the detector class directly. But it's quite easy to realise: just pyramid down your image before train and match.
