### ISSUE TITLE
fusion运行崩溃

### ISSUE THREAD

**Issue by shang720** [meiqua/shape_based_matching#154]
跑test_fusion测试代码，sobel_mag_phase_quant_hist_spread_response_test()这个函数会出现下图崩溃。
![56](https://user-images.githubusercontent.com/26593138/117284791-d0b9d100-ae99-11eb-8838-9f0ebed4a1b0.png)

**Comment by meiqua** [comment]
这是fusion branch里的那个文件吗？我看555行跟这个不一样

**Comment by shang720** [comment]
> 这是fusion branch里的那个文件吗？我看555行跟这个不一样

啊 是我放错文件了 浪费大佬时间了 抱歉==
