### ISSUE TITLE
模板匹配问题请教

### ISSUE THREAD

**Issue by keyxuliang** [meiqua/shape_based_matching#18]
你好，麻烦请教个问题，《machine vision algorithms and applications》中的这一段，方向向量的变换是怎么推理的？

![image](https://user-images.githubusercontent.com/33013417/55696466-a57d0300-59ef-11e9-90a3-33f5016358fd.png)

**Comment by meiqua** [comment]
我不是太懂他这个方向怎么定义的，不过这个仅在x y方向scale不同时有区别，否则(A^-1)T就等于A。因为affine transform可以分解为scale * rotate，而旋转矩阵的转置等于逆。
也就是说一般来说看成A就好了。

**Comment by keyxuliang** [comment]
好的，谢谢

**Comment by meiqua** [comment]
哦，这里这样写应该是方向变换通用公式的意思，A有平移部分也行。[可参考](http://www.songho.ca/opengl/gl_normaltransform.html)

**Comment by keyxuliang** [comment]
3Q
