### ISSUE TITLE
我在使用ICP测试的时候一直出现Link2001，但我明明引用了ICP

### ISSUE THREAD

**Issue by yangsc-notebook** [meiqua/shape_based_matching#181]
严重性	代码	说明	项目	文件	行
错误	LNK2001	无法解析的外部符号 "public: void __cdecl Scene_kdtree::init_Scene_kdtree_cpu(class cv::Mat,class cv::Mat,class KDTree_cpu &,float,float,float)" (?init_Scene_kdtree_cpu@Scene_kdtree@@QEAAXVMat@cv@@0AEAVKDTree_cpu@@MMM@Z)	Project_icp	D:\Test\Project_icp\Project_icp\test.obj	1
严重性	代码	说明	项目	文件	行
错误	LNK2001	无法解析的外部符号 "struct cuda_icp::RegistrationResult __cdecl cuda_icp::sim3::ICP2D_Point2Plane_cpu(class std::vector<struct vec<2,float>,class std::allocator<struct vec<2,float> > > &,struct Scene_kdtree,struct cuda_icp::ICPConvergenceCriteria)" (?ICP2D_Point2Plane_cpu@sim3@cuda_icp@@YA?AURegistrationResult@2@AEAV?$vector@U?$vec@$01M@@V?$allocator@U?$vec@$01M@@@std@@@std@@UScene_kdtree@@UICPConvergenceCriteria@2@@Z)	Project_icp	D:\Test\Project_icp\Project_icp\test.obj	1

**Comment by Liao-lin** [comment]
你好 请问解决了吗 我也遇到了这个问题
