### ISSUE TITLE
How to set the parameters?

### ISSUE THREAD

**Issue by bingyingL** [meiqua/shape_based_matching#2]
In case0,only find out 4 circles in case0/2.jpg by built-in case0/circle_templ.yaml without any modification,but the scores is large than in case0/result/2.png?

**Comment by meiqua** [comment]
Hi, you can change top5 to a larger value in line 83

**Comment by bingyingL** [comment]
Thanks for your great work.it work well, but a  target is detected multiple times.
Non maximum suppression needs to apply.
