### ISSUE TITLE
How to speed up

### ISSUE THREAD

**Issue by selfex22** [meiqua/shape_based_matching#20]
dear meiqua
My Computer is windows10 x64, Visual Studio 2017
I tested the basic example rotation finder.
It took about 5 minutes in train mode and about 3 minutes in test mode. 
In the description, it is said to be less than 100ms.
I am curious about the difference.

Below is test logs Information..
////////////////////////////////////////
test img size: 2355200
construct response map
elasped time:13.9197s
templ matche
lasped time:58.167s
elasped time:72.092s
matches.size(): 9
match.template_id: 340
match.similarity: 99.4141
////////////////////////////////////////

Thank you all the time.

**Comment by meiqua** [comment]
Hi, have you opened SIMD & O2 optimization option in VS?

**Comment by selfex22** [comment]
I enabled the o2 option.(Maximum Optimization) 
but, when enabled the SIMD(SSE or SSE2) option, the below Compiler was occured error .

Error	C3001	'declare': expected an OpenMP directive name	
Error	C3036	'omp_insert': invalid operator token in OpenMP 'reduction' clause	
Error	C3016	'template_id': index variable in OpenMP 'for' statement must have signed integral type

===> Error Lines
#pragma omp declare reduction \
#pragma omp parallel for reduction(omp_insert:matches)

Thank you! meiqua~~

**Comment by selfex22** [comment]
I found my answer in past questions.
Thank you very much.

**Comment by meiqua** [comment]
Nice, glad it helps.
