### ISSUE TITLE
创建模板 可否用当前的特征点进行旋转操作得到360度的特征点？

### ISSUE THREAD

**Issue by qq61786631** [meiqua/shape_based_matching#28]
一直有这个疑问，用单幅图片得到的特征点旋转 和 图片分别旋转取特征  ，这两种方式有什么区别吗？

**Comment by meiqua** [comment]
这个之前在[这里](https://github.com/meiqua/shape_based_matching/issues/10#issuecomment-502374749)讨论过。

**Comment by qq61786631** [comment]
谢谢
