### ISSUE TITLE
如何结合尺度和旋转不变

### ISSUE THREAD

**Issue by wu110011** [meiqua/shape_based_matching#29]
我看到程式码有scale_test()和angle_test()，
请问这两个要如何结合使用呢?
我想要Match同时有尺度和旋转不变，谢谢!

**Comment by meiqua** [comment]
把scale angle的range step两个变量都设定下就行

**Comment by wu110011** [comment]
可以了，感谢!

**Comment by yaoyaolii** [comment]
@wu110011 您好，请问你是怎样将scale 和angle结合使用的呢？
有点没看懂你们的意思，谢谢！

**Comment by wu110011** [comment]
shape_based_matching::shapeInfo_producer shapes(padded_img, padded_mask);
		//angle
		shapes.angle_range = { 0, 45 };
		shapes.angle_step = 3;
		//scale
		shapes.scale_range = { 0.7f, 1 };
		shapes.scale_step = 0.02f;
                shapes.produce_infos();
