### ISSUE TITLE
How  to understand  section3.5 "Linearizing the Memory for Parallelization"?

### ISSUE THREAD

**Issue by keyxuliang** [meiqua/shape_based_matching#3]
Hi,
How to understand functions: "similarity_64" and "accessLinearMemory"?
Thanks!

**Comment by meiqua** [comment]
The key idea is that a feature is just an offset same at all positions, so we will access memory in an every-n manner if we match it directly. After rearranging memory, we can get so-called linear memory, leading to cache-friendly continuous memory access.
accessLinearMemory is a function to get entry pointer of the continuous memory, and similarity_64 uses SSE to speed up.
