### ISSUE TITLE
相似性的计算原理？

### ISSUE THREAD

**Issue by ldepn** [meiqua/shape_based_matching#30]
"Gradient Response Maps for Real-Time Detection of Texture-Less Objects"这篇文章里面的公式2怎么理解？
里面r表示特征点的位置，c表示特征点r的平移量？这里的c是怎么确定的？大括号里面是取c+r的T邻域内的相似性最大，这里的T邻域的中心点为什么是c+r？

**Comment by meiqua** [comment]
c就是模版在测试图像中的位置，c需要覆盖全图像，相当于一个滑动窗口。c+r就是滑动的时候特征点的位置。

**Comment by ldepn** [comment]
嗯嗯，看公式没看出来c是不断增加的，其实就是通过c来进行滑动的
