### ISSUE TITLE
模版生成问题

### ISSUE THREAD

**Issue by dongmiller** [meiqua/shape_based_matching#40]
楼主，我想问一下对于论文里面的模版生成是2000张，他这个生成是怎样的形式啊？以竖直向上为轴旋转360度，一个斜坡的90度，再加上平面上的两个旋转，还有尺度的变换，感觉生成的数量远比2000张多啊～；楼主的例子里面好像都是对于一张图片而言的，如果我想获取一个三维模型的物体的位姿，应该怎么去弄啊？有点浑～想来请教一下

**Comment by meiqua** [comment]
三维有6个自由度，4个维度需要采样（剩下两个就是在图像中匹配的xy），pose三个尺度一个。角度步长很大，不然确实比2000张多很多。要得到三维的模版得把模型渲染出来。

**Comment by dongmiller** [comment]
> 三维有6个自由度，4个维度需要采样（剩下两个就是在图像中匹配的xy），pose三个尺度一个。角度步长很大，不然确实比2000张多很多。要得到三维的模版得把模型渲染出来。

那这样应该是我需要在楼主的代码基础上，先由渲染模型获取整体的多个模版信息（比如2000张的模版），然后再去匹配整体的模版吗？？应该是这样的思路吧？其实我之前有看到https://github.com/imbinwang/LINE2D这个代码，但是跑的时候总是失效，然后就看到楼主这个了～；

**Comment by dongmiller** [comment]
> 三维有6个自由度，4个维度需要采样（剩下两个就是在图像中匹配的xy），pose三个尺度一个。角度步长很大，不然确实比2000张多很多。要得到三维的模版得把模型渲染出来。

那这样应该是我需要在楼主的代码基础上，先由渲染模型获取整体的多个模版信息（比如2000张的模版），然后再去匹配整体的模版吗？？应该是这样的思路吧？其实我之前有看到https://github.com/imbinwang/LINE2D  这个代码，但是跑的时候总是失效，然后就看到楼主这个了～；

**Comment by meiqua** [comment]
是的，如果只需要深度的话渲染器可以参考[我之前写的](https://github.com/meiqua/patch_linemod)

**Comment by dongmiller** [comment]
> 是的，如果只需要深度的话渲染器可以参考[我之前写的](https://github.com/meiqua/patch_linemod)

是我理解错了吗？为什么是需要深度？如果我本身就只有rgb相机拍摄到的彩色图去做位姿检测，应该是渲染模型的rgb图作为模版吧？（应该不是完全的linemod，是省略了深度图的line2d吧？）

**Comment by meiqua** [comment]
对于无纹理的物体，拿深度图得到mask来训练一样的

**Comment by dongmiller** [comment]
> 对于无纹理的物体，拿深度图得到mask来训练一样的

嗯嗯 好的 谢谢～
