### ISSUE TITLE
生成方案时出错

### ISSUE THREAD

**Issue by zhoujinhai** [meiqua/shape_based_matching#41]
生成时，出现以下错误，怎么修改？？？

![image](https://user-images.githubusercontent.com/20365125/63499290-21d53600-c4fa-11e9-8492-1ac51106dbda.png)

**Comment by meiqua** [comment]
> To turn off the warning for an entire project in the Visual Studio IDE:
\
Open the Property Pages dialog for your project. For information on how to use the Property Pages dialog, see Property Pages.
Select the Configuration Properties, C/C++, Advanced page.
Edit the Disable Specific Warnings property to add 4996. Choose OK to apply your changes.

**Comment by zhoujinhai** [comment]
@meiqua thanks.
