### ISSUE TITLE
训练报错问题

### ISSUE THREAD

**Issue by KangWang1991** [meiqua/shape_based_matching#49]
我在尝试自己训练时，在模板保存时发生错误。查看opencv  FileStorage类也找不到具体原因。`void Detector::writeClass(const std::string &class_id, FileStorage &fs) const
{
    TemplatesMap::const_iterator it = class_templates.find(class_id);
    CV_Assert(it != class_templates.end());
    const std::vector<TemplatePyramid> &tps = it->second;

    fs << "class_id" << it->first;
    fs << "pyramid_levels" << pyramid_levels;
    fs << "template_pyramids"
       << "[";
    for (size_t i = 0; i < tps.size(); ++i)
    {
        const TemplatePyramid &tp = tps[i];
        fs << "{";
        fs << "template_id" << int(i); //TODO is this cast correct? won't be good if rolls over...
        fs << "templates"`
运行到fs << "templates"这里就出现错误：0x00007FF80450A839 处(位于 test2.exe 中)有未经处理的异常: Microsoft C++ 异常: cv::Exception，位于内存位置 0x0000005FA06FE320 处。

请问是什么原因导致的呢？

**Comment by meiqua** [comment]
意思是默认的可以训练吗？那可能是保存的名字后缀不对，或者保存的地方没有权限写入？

**Comment by KangWang1991** [comment]
bebug下一直提示未加载opencv_world300d.pdb,找了下是未加载调试信息模块？尝试在release下成功了。谢谢。

另外我问下匹配得到的角度即是template_id对吗？

**Comment by meiqua** [comment]
不是，要根据id查。

**Comment by KangWang1991** [comment]
按1度来进行训练的，id不是角度吗？从哪里可以由id获取当前模板的角度属性呢？找不到获取函数或者参数属性。

**Comment by meiqua** [comment]
存[这了](https://github.com/meiqua/shape_based_matching/blob/0fb61ac102d82c55e8b77b8c816691ab6e63d7ef/test.cpp#L277)
