### ISSUE TITLE
对应点

### ISSUE THREAD

**Issue by Moonstarwork** [meiqua/shape_based_matching#5]
请问怎找test图像 与 train图像的对应点呢？然后进行配准呢？ 不知道问题是否合适？

**Comment by Moonstarwork** [comment]
感谢分享，读者先自己研究一下

**Comment by faithzxr** [comment]
> 请问怎找test图像 与 train图像的对应点呢？然后进行配准呢？ 不知道问题是否合适？

您知道怎么找到对应点了嘛？
