### ISSUE TITLE
图像padding的大小的决定因素

### ISSUE THREAD

**Issue by JackLee1** [meiqua/shape_based_matching#50]
meiqua：
           再咨询一下，看了你的程序，无论在训练过程还是检测过程中，输入图片的四周padding的非常的大，在一定程度上影响了时间开销。按照我的理解，训练过程图片padding的大小只是由训练图片大小和旋转角度决定，保证训练图片经过旋转后，能够在padding范围之内。在检测过程中，只需要保证输入图片padding不小于训练的padding大小，另外为了计算上的考量，padding后的图片大小为16字节对齐即可，以此为依据设置训练和检测过程的padding大小。
           不知这样来设计padding大小的想法对不对？

**Comment by meiqua** [comment]
训练的理解是对的。检测不用padding，这里纯粹是为了把图像搞大点测速度。现在的16字节对齐是通过切点图像保证的，稍微padding下对齐也行。

**Comment by JackLee1** [comment]
知道了，谢谢。
