### ISSUE TITLE
关于最终定位精度

### ISSUE THREAD

**Issue by zhengli233** [meiqua/shape_based_matching#51]
我看了一遍代码，在匹配时，滑动窗口的步幅是以T为单位的。那么最终定位的精度是不是就会有0~T个像素的差？

**Comment by meiqua** [comment]
是的，最大T/2吧

**Comment by zhengli233** [comment]
谢谢。
另外，我发现角度的精度似乎不太好确定，一方面模板中的特征点到旋转中心的距离是不确定的，有可能旋转1度就超出了T/2的范围，也有可能5度才超过；另一方面，去重时比较Match是否一样只对比了x，y和score，最终留在结果中的Match与它被放入matches中的时序有关。
有办法在角度上更精确么

**Comment by meiqua** [comment]
角度来说确实没法确定采样的步长，只能根据模板大小大概反算一下
