### ISSUE TITLE
scale测试不够精确问题

### ISSUE THREAD

**Issue by tuner24** [meiqua/shape_based_matching#57]
你好，我在 scale_test 中有把模版图画到图像上，但是模版mask总是偏小一些，请问这是算法的正常结果还是我画图的代码有问题？
![Screen Shot 2019-10-18 at 3 45 01 PM](https://user-images.githubusercontent.com/7548501/67075958-d1f3b200-f1be-11e9-83a6-fdf766e2d6b4.png)

**Comment by meiqua** [comment]
偏小应该是因为templ[0]的长宽总是小一点，因为templ[0]的长宽是边缘点的bbox，如果没选上最旁边的点就不一定刚好框住mask。最好通过存好的scale跟angle信息来，具体的变换可以参考[这个文件](https://github.com/meiqua/shape_based_matching/blob/master/Transforms%20in%20shape-based%20matching.pdf)。

**Comment by tuner24** [comment]
> 偏小应该是因为templ[0]的长宽总是小一点，因为templ[0]的长宽是边缘点的bbox，如果没选上最旁边的点就不一定刚好框住mask。最好通过存好的scale跟angle信息来，具体的变换可以参考[这个文件](https://github.com/meiqua/shape_based_matching/blob/master/Transforms%20in%20shape-based%20matching.pdf)。

谢谢解答，改了一下，好多了，但是还是有些问题。 
有点复杂！！！
我再看看吧。
