### ISSUE TITLE
匹配精度

### ISSUE THREAD

**Issue by tzhang2014** [meiqua/shape_based_matching#6]
感谢楼主的分享，我在实际测试中将两张一模一样的图片进行匹配，最终的结果有误差，请问这是正常现象吗？谢谢

**Comment by meiqua** [comment]
是的，为了加速匹配有一个量化过程，最终精度像素角度误差大概在个位数。halcon在匹配后有个简单的local refinement，精度说是能到0.1像素 0.1度的量级。可以参考：
[Performance Evaluation, chapter 2.7](https://iuks.in.tum.de/_media/members/steger/publications/2002/pf-2002-01-ulrich-steger.pdf)

**Comment by tzhang2014** [comment]
![train](https://user-images.githubusercontent.com/19585245/51307923-dd714b80-1a7b-11e9-8cb8-5c0ceadb2b95.jpg)  ，ROI 是1077, 1087, 465, 465 ，
![test](https://user-images.githubusercontent.com/19585245/51307953-f1b54880-1a7b-11e9-96d1-66a629af2bab.jpg)

**Comment by tzhang2014** [comment]
楼主，我用最上面的作为模板，ROI区域为1077, 1087, 465, 465， 用最下面的图片作为test以及用原图作为test， 用的angle_test(),匹配结果都是0,请问下可能是什么原因呢，谢谢

**Comment by meiqua** [comment]
应该是模板点选太多训练失败，可以试试少选点。就是detector第一个参数

**Comment by meiqua** [comment]
我试了下，超过31个点并且得分都是100会overflow... 这是MIPP引入的限制，我改了改，最新的没问题了，选60个点匹配，结果很完美

**Comment by tzhang2014** [comment]
非常感谢楼主，正在修正角度误差

**Comment by tzhang2014** [comment]
楼主，哪个修正角度的是在得到匹配点过后，再用匹配的特征的与所有模板的特征点进行最小二乘吗？谢谢

**Comment by meiqua** [comment]
差不多，模版特征点对应最近的测试图像的canny边缘点。类似point to plane icp。

**Comment by ScottYang1982** [comment]
这个修正具体怎么实现呢？匹配的结果里只有match.x,match.y，并没有匹配的特征啊，icp的两组数据应该怎么选择呢？谢谢

**Comment by ScottYang1982** [comment]
而且这个match.x,match.y,指哪个点？画的矩形直接加宽高，不考虑旋转么？

**Comment by meiqua** [comment]
@ScottYang1982 匹配的特征点是从训练的模板拿到的：[例子](https://github.com/meiqua/shape_based_matching/blob/3c75a25534f7c79b0c91fc237a130717a86fb181/test.cpp#L320)  ，对应每个点找canny边缘点即可；
match.x/y指训练图像crop后(切掉没有特征点的黑边)的topleft在测试图像中的位置，crop时bounding box的topleft存在templ[0].tl_x/y里；
在匹配中是没有旋转的概念的，旋转信息是事先存在infos_have_templ里。旋转以crop前的训练图像中心为旋转中心。

**Comment by ScottYang1982** [comment]
多谢解答，但是这就存在一个问题，匹配后的矩形中心实际上并不是训练图像的中心，若训练图像中心是识别的目标点那每次就不一样了

**Comment by meiqua** [comment]
@tzhang2014 是的，不过可以通过存好的信息补偿回来。crop主要是为了防止黑边过大导致匹配的时候右方跟下方要让的位置太多(模板图像右边跟下边不能超出测试图像右边跟下边)。

**Comment by ScottYang1982** [comment]
@meiqua 您太专业了，现在我明白了，

**Comment by oUp2Uo** [comment]
@meiqua 您好，想请问下这个实际旋转的角度应该怎么计算呢？
假设我scale设置就是1，那么相当于没有尺度变化，这样得到的match.x/y给出的就是和测试图像的横纵向偏移。这时候角度应该怎样去推呢？
如果有scale的话，match.template_id也不能正确的找到是第几个scale（因为会有-1），这么理解对吗？
谢谢

**Comment by meiqua** [comment]
@oUp2Uo 角度跟尺度都是在训练时记录好的，通过match id在 infos_have_templ里面取。示例里直接把id当角度是为了图方便，可能有点误导。我改了下，现在是 infos[match.template_id].angle 来取角度。

**Comment by ScottYang1982** [comment]
@meiqua 这个实现把原论文里的small translation and deformation 也实现了么？

**Comment by ScottYang1982** [comment]
@meiqua 也就是在某一点处的 gradient orientation 是否考虑了邻域的值？反复测试发现只要相似分值打发到7.80效果就很差，误识别很多

**Comment by meiqua** [comment]
@ScottYang1982 变形鲁棒性是通过方向扩散实现的，类似边缘膨胀。误识别我也测试过，经常在小物体模版点很少时出现。这个也好理解，少了就容易被干扰。

**Comment by ScottYang1982** [comment]
@meiqua 嗯，特征选多了，又容易不识别，因为里面有何判断少于特征点模板就无法创建成功，看来要找个合适的number of features

**Comment by oUp2Uo** [comment]
@meiqua 感谢回答。
请问画框是否需要加上scale的系数？类似于 cv::RotatedRect rotatedRectangle({ x, y }, { r * 2 * infos[match.template_id].scale, r * 2 * infos[match.template_id].scale }, -infos[match.template_id].angle);

**Comment by meiqua** [comment]
@oUp2Uo 对的，严格来说是需要的，我加上了，多谢建议

**Comment by oUp2Uo** [comment]
@meiqua 我试了一下，画框的起点的x,y在计算的时候，貌似模板的宽度和padding大小不用乘这个scale。如果方便的话可以解答一下这是为什么呢？有点没理解

**Comment by meiqua** [comment]
@oUp2Uo 这里其实有两条线，一个是训练时候的数据，一个是匹配出来的数据；匹配的数据跟scale 旋转无关，训练的数据时候是相关的；
起点x y，templ[0]. tl_x/y .features 都属于匹配出来的数据，不需要scale；
框的长度270属于训练时候的数据，需要scale再旋转；
padding一直是固定的，训练时候没动，也不需要scale。

**Comment by oUp2Uo** [comment]
@meiqua 所以这里的 270/2.0f，其实也是需要scale的？

> float x =  match.x - templ[0].tl_x + 270/2.0f + 100;
> float y =  match.y - templ[0].tl_y + 270/2.0f + 100;

**Comment by meiqua** [comment]
@oUp2Uo 没错 我回复完就回头改了^_^

**Comment by oUp2Uo** [comment]
@meiqua 但我这么试了一下，貌似结果不对……不乘的时候看着是对的……

**Comment by meiqua** [comment]
@oUp2Uo 额，我理解错了，那里不能乘，因为scale的时候其实侵占了padding的位置（这也是padding的原因），总大小不变。大小是warpaffine最后一个参数决定的：
``` c++
cv::warpAffine(src, dst, rot_mat, src.size());
```

**Comment by oUp2Uo** [comment]
@meiqua 所以是只需要改画框的地方，对吧

**Comment by meiqua** [comment]
@oUp2Uo 恩

**Comment by oUp2Uo** [comment]
@meiqua 哦哦，好的，谢谢解答~

**Comment by ScottYang1982** [comment]
@meiqua strong_threshold 只是为了减少比较的点数吧？直接决定了feature number，很多时候无法识别就是因为特征点不足吧？

**Comment by meiqua** [comment]
@ScottYang1982 这里是默认训练图像是光照清晰的图像，用strong_threshold比较好，当然，也可以根据情况降低阈值；点数往往由训练图像大小决定，无法提模版本质是因为确实拿过于小的物体没办法。

**Comment by ScottYang1982** [comment]
@meiqua, 如何使用icp 进行精调呢，我寻找特征点最近的边缘上的任何一点就可以了么？不需要考虑这个最近点的梯度信息？能否说的具体点呢如何使用icp在这里的情况下，🙏

**Comment by meiqua** [comment]
@ScottYang1982 是的，找最近点，再用梯度计算误差，最后解一个最小二乘方程

**Comment by meiqua** [comment]
@ScottYang1982 刚好最近[3d cuda icp](https://github.com/meiqua/pose_refine)写的差不多了，花了点时间移植到2D的情况，最后跑出来效果确实不错，要用的话可以参考下面两个branch。
[icp2D branch](https://github.com/meiqua/shape_based_matching/tree/icp2D)，误差初步测试在0.1到0.5 degree
[icp + subpixel branch](https://github.com/meiqua/shape_based_matching/tree/subpixel)，误差 <0.1 degree

**Comment by ScottYang1982** [comment]
@meiqua 多谢！但是在编译时报错：

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | C2893 | Failed to specialize function template 'cuda_icp::RegistrationResult cuda_icp::ICP2D_Point2Plane_cpu(std::vector<Vec2f,std::allocator<_Ty>> &,const Scene,const cuda_icp::ICPConvergenceCriteria)'

**Comment by meiqua** [comment]
@ScottYang1982 看来MSVC不如GCC智能。加了个前置声明，新代码应该好了
