### ISSUE TITLE
fusion branch 出现mipp::mul<int32_t> (SSE3) is undefined!错误

### ISSUE THREAD

**Issue by qq61786631** [meiqua/shape_based_matching#68]
如题，运行出现下面的错误，sse3没定义嘛~大神帮看看呢，谢谢。
MIPP tests
----------

Instr. type:       SSE
Instr. full type:  SSE3
Instr. version:    3
Instr. size:       128 bits
Instr. lanes:      1
64-bit support:    yes
Byte/word support: yes
in this SIMD, int8 max is not inplemented by MIPP
in this SIMD, int8 shuff is not inplemented by MIPP
----------

test img size: 1044480

terminate called recursively
terminate called recursively
terminate called after throwing an instance of 'std::runtime_error'
  what():  mipp::mul<int32_t> (SSE3) is undefined!
terminate called recursively
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by qq61786631** [comment]
win10 qt mingw64

**Comment by meiqua** [comment]
Yes, the fusion branch is under development, so there may exist some bugs and speed issues now.
