### ISSUE TITLE
如何将64个特征点增加到8192个特征点

### ISSUE THREAD

**Issue by godlovehill** [meiqua/shape_based_matching#69]
你好，请问8192个特征点是如何得到的呢？计算的依据是什么，谢谢。

**Comment by meiqua** [comment]
主要是得分不能超过2的16次方，否则就溢出了

**Comment by godlovehill** [comment]
8192是怎么得到的，能否讲的具体一些呢，期待您的回复

**Comment by meiqua** [comment]
一个点最高4分，int16_t类型最大值32767，所以不能超过8192。一般也不会这么多。
