### ISSUE TITLE
匹配的速度问题

### ISSUE THREAD

**Issue by CaffeMrDe** [meiqua/shape_based_matching#8]

**Comment by CaffeMrDe** [comment]
为什么我的win7机器跑的 angle_test例程，模板为100*100，兴趣点为20个，图像为200*200，mode= test的时候，读取yaml模型已经耗时10s,识别的时候耗时50s,时间太长。这个可以提高速度吗？

**Comment by meiqua** [comment]
一般来说慢一点是因为没开03，不过这么慢我倒是没见过，这么大的图像50ms还差不多。有可能是机器的问题，可以试试在别的地方跑。

**Comment by CaffeMrDe** [comment]
首先，感谢up主的神速回复
我的log 信息是
MIPP tests" << std::endl;
----------" << std::endl << std::endl;

"Instr. type:       NO
Instr. full type:  NO_INTRINSICS
Instr. version:    1
Instr. size:       0bit
Instr. lanes:      1
"64-bit support:    yes
Byte/word support:  yes

in this SIMD, int8 max is not inplemented by MIPP
in this SIMD, int8 shuff is not inplemented by MIPP

test img size: 1 6792192

construct response map
elasped time:137.849s

templ match
elasped time:47.1369s

elasped time:185.022s

matches.size() :2003

平台为 win7 vs2015 opencv 3.4.1

希望up主能给个反馈，谢谢

**Comment by CaffeMrDe** [comment]
up主所讲的“因为没开03”  是指 什么 呢？

**Comment by meiqua** [comment]
o3简单来说就是让编译器按速度最快的方式编译。  
按log来看，可能的问题有：  
vs没开SIMD选项；没开优化选项；没开openmp；  
另外就是图像太大了，1600万像素，真的有必要这么大吗？
选的点太少导致特征不明显？最后2000个候选有点多了。

**Comment by zhoujinhai** [comment]
My speed is slower!!!
![image](https://user-images.githubusercontent.com/20365125/63513464-e5fd9900-c518-11e9-8b07-71964a55fbb6.png)
