### ISSUE TITLE
还请大神出个支持OpenCV 4和Python的呀

### ISSUE THREAD

**Issue by JimXu1989** [meiqua/shape_based_matching#82]
这个代码太好了，大神能不能出个python版的呀

**Comment by meiqua** [comment]
opencv4应该不用改什么，python我抽时间写下

**Comment by meiqua** [comment]
可以参考[python_binding branch](https://github.com/meiqua/shape_based_matching/tree/python_binding)，readme里有安装步骤。

**Comment by JimXu1989** [comment]
> 可以参考[python_binding branch](https://github.com/meiqua/shape_based_matching/tree/python_binding)，readme里有安装步骤。

CMake Error at CMakeLists.txt:31 (find_package):
  Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "3".

  The following configuration files were considered but not accepted:

    G:/opencv/opencv-4.3.0/build/install/OpenCVConfig.cmake, version: 4.3.0
    G:/opencv/opencv-4.3.0/build/OpenCVConfig.cmake, version: 4.3.0
大神，遇到这个问题应该怎么办呀？

**Comment by meiqua** [comment]
改成4呗

**Comment by JimXu1989** [comment]
> 改成4呗

好的，我改一下哈，谢谢大神

**Comment by zhashung** [comment]
另外，test.cpp中325行中CV_GRAY2BGR需要改成COLOR_GRAY2BGR。

**Comment by zhashung** [comment]
除了上面修改cmake文件，把我上面提到的test.cpp中的修改完，作者的代码就可以编译成功了。
