### ISSUE TITLE
inv_light匹配问题

### ISSUE THREAD

**Issue by qq61786631** [meiqua/shape_based_matching#87]
您好，在用inv_light 进行极性匹配时候，发现对原模板图片进行查找，结果差的比较大（蓝色点），用ICP2D_Point2Plane_cpu 差距变得更大（绿色点），实在想不通这是啥原因~楼主能帮忙分析下吗。

贴上两张截图

![360截图168409237396119](https://user-images.githubusercontent.com/34880475/84584182-a8655600-ae33-11ea-8e0f-3b425153f1f3.png)

![360截图18720122355338](https://user-images.githubusercontent.com/34880475/84583869-9504bb80-ae30-11ea-83eb-5899042d472f.png)

原图

![X1](https://user-images.githubusercontent.com/34880475/84584350-e5cae300-ae35-11ea-9df9-77554a8bb264.png)

**Comment by meiqua** [comment]
跟inv_light关系不大，估计是像素距离太远，最近点搜不到。init_Scene_edge_cpu的时候把第三个参数加上（默认是4），比如init_Scene_edge_cpu(**, **, 8)

**Comment by qq61786631** [comment]
非常感谢
