### ISSUE TITLE
请问这个在ubuntu16.04系统能跑吗？

### ISSUE THREAD

**Issue by longzeyilang** [meiqua/shape_based_matching#9]
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.
出现这样错误？请问如何解决？

**Comment by meiqua** [comment]
这个本来就是在ubuntu上用的。我不太清楚你打的什么命令，一般cmake是这几个：
``` shell
mkdir build
cd build
cmake ..
make
./shape_based_matching_test
```

**Comment by longzeyilang** [comment]
已经弄好

**Comment by longzeyilang** [comment]
mipp::orb(src_v, dst_v)是什么含义？

**Comment by longzeyilang** [comment]
你好，没有看懂整个匹配原理和流程，楼主能否讲讲？期待。。
