### ISSUE TITLE
单层匹配

### ISSUE THREAD

**Issue by raindropstarbucks** [meiqua/shape_based_matching#90]

**Comment by raindropstarbucks** [comment]
作者你好，如果只是想做粗匹配不做精匹配，是否等效于将步长{4,8}改成{8}，然后将图像和模板长宽都缩小到原来的1/2？

**Comment by meiqua** [comment]
是的，要看想粗略到什么程度，极限是缩小到刚好看得清，stride刚好没出现误匹配。

**Comment by raindropstarbucks** [comment]
但是这样的情况有个奇怪的点是，match的耗时增加了，即当我在缩小的图上做全局匹配加上在原图上做精匹配的时候match耗时是80ms，然而当我将步长{4,8}改成{8}，图像和模板长宽缩小到1/2的时候（相当于只在缩小的图上做全局匹配），Match的耗时是190ms

**Comment by meiqua** [comment]
变量控制的一致吗？比如双层匹配时，高层只会提取一半的点，单层可能多选了一倍？

**Comment by raindropstarbucks** [comment]
是的，我忽略了这一点，单层多选了一倍，选对的情况下单层的match比双层的match耗时稍微长一点点，match部分的主要耗时在粗匹配部分
