### ISSUE TITLE
同时缩放和旋转检测

### ISSUE THREAD

**Issue by JackLee1** [meiqua/shape_based_matching#98]
meiqua：
             我在angle_test函数中设置scale_range的范围，同时进行图像缩放与旋转检测，在对图像进行训练后，执行目标检测操作时，居然检测不到目标，这是什么原因？

**Comment by JackLee1** [comment]
调试了一下代码，现在改好了：
		float first_scale = 1.0f;        //add
		for (auto& info : shapes.infos) {
			Mat to_show = shapes.src_of(info);

			std::cout << "\ninfo.angle: " << info.angle << "   info.scale: " << info.scale << std::endl;
			int templ_id;

			if (is_first || (first_scale != info.scale)) {        //add
				templ_id = detector.addTemplate(shapes.src_of(info), class_id, shapes.mask_of(info));
				first_id = templ_id;
				first_angle = info.angle;
				first_scale = info.scale;        //add
				if (use_rot) is_first = false;
			}

**Comment by jincanchen** [comment]
nice!
